### ISSUE TITLE
Fallocate vs. dd zero

### ISSUE THREAD

**Issue by LukeHandle** [sowbug/mkeosimg#4]
Would using `fallocate` instead of `dd` to create the zeroed image make sense?

I saw this blog post suggest as such: https://www.kc8apf.net/2018/01/ubiquiti-edgerouter-lite-usb-surgery/

I've seen issues when using fallocate for swap, but I would not expect an issue here? Would be much faster.

**Comment by sowbug** [comment]
@LukeHandle and @ianhodgson thank you. I tried Ian's mod to `dd`, and it seems to work. `mkeosimg` produces a same-sized file with minimal differences that appear to be `parted` inserting volume serial numbers and/or timestamps for each subsequent run; otherwise it appears that checksums would match.

I am not making changes to `mkeosdrive` because that's a physical volume, not a virtual one, so we're already doing the right amount of work.

**Comment by sowbug** [comment]
That said, I haven't tested this (I don't have a Ubiquiti setup anymore), so I'd appreciate some verification.

**Comment by ianhodgson** [comment]
Got around to testing.  The image produced with all three versions of the dd command are the same apparent size and behave the same when used to boot an erlite.

Took another moment to think about this, and I think I've made the script a little harder to read.  Seek is a very strange place to have a unit in dd, I'd like to move it to block size where it should have been.  Pull #9 has been submitted to change this.
