### ISSUE TITLE
Add support for WireGuard/wireguard-vyatta-ubnt

### ISSUE THREAD

**Issue by Chaz6** [sowbug/mkeosimg#6]
I would like to install wireguard support on my edgerouter, and to make it easier to restore when the flash dies, it would be really useful to be able to create a disk image with the wireguard software pre-configured.

https://github.com/WireGuard/wireguard-vyatta-ubnt

**Comment by sowbug** [comment]
@Chaz6 I hear you, but it would have to be a low-effort fix, and I'm guessing that it's not (since your report suggests that it's not already setting up Wireguard on the new image).

This tool really just takes the firmware upgrade image and sprays whatever's in the EdgeRouter backup file into its filesystem. If Wireguard isn't included in the backup file, then the tool would have to go fetch it from somewhere. And at that point this tool becomes a sort of offline package-management system, rather than just a simple script, which would be beyond its tiny scope.
